export const themeFonts = [
  'Readex Pro',
  'Manrope',
  'Open Sans',
  'Lato',
  'Overpass',
  'Source Sans Pro',
  'DM Sans',
  'Arial',
  'Tahoma',
  'Trebuchet MS ',
  'Verdana' ,
  'System UI',
  'Serif',
  'Fraunces',
  'DM Serif Display',
  'Josefin Slab',
  'Times New Roman ',
  'Georgia',
  'Palatino',
  'Lucida Bright ',
  'Monospace',
  'Azeret Mono',
  'Space Mono',
  'Courier New',
  'Lucida Sans Typewriter'
]